/**
 * Single HTTP entry point that impersonates a Supabase project URL for the app:
 *   /rest/v1/*     -> PostgREST (reverse proxy)
 *   /auth/v1/*     -> fake GoTrue backed by auth.users in the local Postgres
 *   /storage/v1/*  -> file store under .demo/storage
 * Run directly (`tsx scripts/demo/gateway.ts`) or through scripts/demo/start.ts.
 */
import { writeFileSync } from "node:fs";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";

import { handleAuth } from "./auth";
import {
  CRON_SECRET,
  EMAIL_FROM,
  ENV_FILE,
  GATEWAY_HOST,
  GATEWAY_PORT,
  GATEWAY_URL,
  PG_URL,
  SITE_URL,
} from "./config";
import { closePool } from "./db";
import { sendEmpty, sendJson } from "./http";
import { apiKey } from "./jwt";
import { proxyToPostgrest } from "./rest-proxy";
import { handleStorage } from "./storage";

export const ANON_KEY = apiKey("anon");
export const SERVICE_ROLE_KEY = apiKey("service_role");

export function writeEnvFile(): string {
  const lines = [
    "# Generated by scripts/demo/gateway.ts for the local demo stack. Copy to .env.local.",
    `NEXT_PUBLIC_SUPABASE_URL=${GATEWAY_URL}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}`,
    `SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}`,
    `SUPABASE_DB_URL=${PG_URL}`,
    `NEXT_PUBLIC_SITE_URL=${SITE_URL}`,
    `CRON_SECRET=${CRON_SECRET}`,
    `EMAIL_FROM="${EMAIL_FROM}"`,
    "ANTHROPIC_API_KEY=",
    "OPENAI_API_KEY=",
    "RESEND_API_KEY=",
    "NEXT_PUBLIC_ANALYTICS_PROVIDER=none",
    "",
  ];
  writeFileSync(ENV_FILE, lines.join("\n"));
  return ENV_FILE;
}

async function route(req: IncomingMessage, res: ServerResponse): Promise<void> {
  const url = new URL(req.url ?? "/", GATEWAY_URL);
  if (req.method === "OPTIONS") return sendEmpty(res, 204);
  const { pathname } = url;

  if (pathname === "/rest/v1" || pathname.startsWith("/rest/v1/"))
    return proxyToPostgrest(req, res, url, "/rest/v1");
  if (pathname.startsWith("/auth/v1/")) {
    if (await handleAuth(req, res, url, pathname.slice("/auth/v1/".length))) return;
    return sendJson(res, 404, {
      code: 404,
      error_code: "not_found",
      msg: `Unknown auth endpoint ${req.method} ${pathname}`,
    });
  }
  if (pathname.startsWith("/storage/v1/")) {
    if (await handleStorage(req, res, url, pathname.slice("/storage/v1/".length))) return;
    return sendJson(res, 404, {
      statusCode: "404",
      error: "not_found",
      message: `Unknown storage endpoint ${req.method} ${pathname}`,
    });
  }
  if (pathname === "/" || pathname === "/health") {
    return sendJson(res, 200, {
      ok: true,
      services: ["rest", "auth", "storage"],
      url: GATEWAY_URL,
    });
  }
  sendJson(res, 404, {
    error: "not_found",
    message: `${req.method} ${pathname} is not served by the demo gateway`,
  });
}

export function startGateway(): Promise<Server> {
  const server = createServer((req, res) => {
    route(req, res).catch((error: unknown) => {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`[gateway] ${req.method} ${req.url}: ${message}`);
      if (!res.headersSent) sendJson(res, 500, { error: "internal_error", message });
      else res.end();
    });
  });
  return new Promise((resolve, reject) => {
    server.once("error", reject);
    server.listen(GATEWAY_PORT, GATEWAY_HOST, () => {
      const envFile = writeEnvFile();
      console.log(`[gateway] listening on ${GATEWAY_URL}`);
      console.log(`[gateway] anon key:         ${ANON_KEY}`);
      console.log(`[gateway] service_role key: ${SERVICE_ROLE_KEY}`);
      console.log(`[gateway] wrote ${envFile}`);
      resolve(server);
    });
  });
}

export async function stopGateway(server: Server): Promise<void> {
  await new Promise<void>((resolve) => server.close(() => resolve()));
  await closePool();
}

const runDirectly = process.argv[1]?.endsWith("gateway.ts") ?? false;
if (runDirectly) {
  startGateway()
    .then((server) => {
      const shutdown = () => stopGateway(server).finally(() => process.exit(0));
      process.on("SIGINT", shutdown);
      process.on("SIGTERM", shutdown);
    })
    .catch((error: unknown) => {
      console.error(error instanceof Error ? error.message : error);
      process.exit(1);
    });
}
