// Generated by scripts/gen-types-local.ts from supabase/migrations. Do not edit by hand.
// Regenerate with `npm run db:types` (linked project) or `npx tsx scripts/gen-types-local.ts`.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "13"
  }
  public: {
    Tables: {
      admin_activity: {
        Row: {
          id: string
          actor_user_id: string
          action: string
          entity_type: string
          entity_id: string | null
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          actor_user_id: string
          action: string
          entity_type: string
          entity_id?: string | null
          metadata?: Json
          created_at?: string
        }
        Update: {
          id?: string
          actor_user_id?: string
          action?: string
          entity_type?: string
          entity_id?: string | null
          metadata?: Json
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_activity_actor_user_id_fkey"
            columns: ["actor_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      ai_usage: {
        Row: {
          id: string
          feature: string
          model: string
          input_tokens: number
          output_tokens: number
          cost_estimate: number
          actor_user_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          feature: string
          model: string
          input_tokens?: number
          output_tokens?: number
          cost_estimate?: number
          actor_user_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          feature?: string
          model?: string
          input_tokens?: number
          output_tokens?: number
          cost_estimate?: number
          actor_user_id?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_usage_actor_user_id_fkey"
            columns: ["actor_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      application_events: {
        Row: {
          id: string
          application_id: string
          from_status: Database["public"]["Enums"]["application_status"] | null
          to_status: Database["public"]["Enums"]["application_status"]
          note: string | null
          actor_user_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          application_id: string
          from_status?: Database["public"]["Enums"]["application_status"] | null
          to_status: Database["public"]["Enums"]["application_status"]
          note?: string | null
          actor_user_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          application_id?: string
          from_status?: Database["public"]["Enums"]["application_status"] | null
          to_status?: Database["public"]["Enums"]["application_status"]
          note?: string | null
          actor_user_id?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "application_events_actor_user_id_fkey"
            columns: ["actor_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "application_events_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          }
        ]
      }
      application_fit: {
        Row: {
          application_id: string
          status: string
          score: number | null
          summary: string | null
          strengths: string[]
          gaps: string[]
          evidence: Json
          model: string | null
          prompt_version: string | null
          inputs_hash: string | null
          attempts: number
          last_error: string | null
          computed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          application_id: string
          status?: string
          score?: number | null
          summary?: string | null
          strengths?: string[]
          gaps?: string[]
          evidence?: Json
          model?: string | null
          prompt_version?: string | null
          inputs_hash?: string | null
          attempts?: number
          last_error?: string | null
          computed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          application_id?: string
          status?: string
          score?: number | null
          summary?: string | null
          strengths?: string[]
          gaps?: string[]
          evidence?: Json
          model?: string | null
          prompt_version?: string | null
          inputs_hash?: string | null
          attempts?: number
          last_error?: string | null
          computed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "application_fit_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: true
            referencedRelation: "applications"
            referencedColumns: ["id"]
          }
        ]
      }
      applications: {
        Row: {
          id: string
          job_id: string
          candidate_id: string
          status: Database["public"]["Enums"]["application_status"]
          source: Database["public"]["Enums"]["application_source"]
          cover_note: string | null
          contact_requested_at: string | null
          contact_released: boolean
          contact_released_by: string | null
          contact_released_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          job_id: string
          candidate_id: string
          status?: Database["public"]["Enums"]["application_status"]
          source?: Database["public"]["Enums"]["application_source"]
          cover_note?: string | null
          contact_requested_at?: string | null
          contact_released?: boolean
          contact_released_by?: string | null
          contact_released_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          job_id?: string
          candidate_id?: string
          status?: Database["public"]["Enums"]["application_status"]
          source?: Database["public"]["Enums"]["application_source"]
          cover_note?: string | null
          contact_requested_at?: string | null
          contact_released?: boolean
          contact_released_by?: string | null
          contact_released_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "applications_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "applications_contact_released_by_fkey"
            columns: ["contact_released_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "applications_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          }
        ]
      }
      assessment_answers: {
        Row: {
          id: string
          attempt_id: string
          question_id: string
          answer_text: string | null
          selected_option: string | null
          likert_value: number | null
          audio_path: string | null
          audio_duration_seconds: number | null
          transcript: string | null
          ai_feedback: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          attempt_id: string
          question_id: string
          answer_text?: string | null
          selected_option?: string | null
          likert_value?: number | null
          audio_path?: string | null
          audio_duration_seconds?: number | null
          transcript?: string | null
          ai_feedback?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          attempt_id?: string
          question_id?: string
          answer_text?: string | null
          selected_option?: string | null
          likert_value?: number | null
          audio_path?: string | null
          audio_duration_seconds?: number | null
          transcript?: string | null
          ai_feedback?: Json | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "assessment_answers_attempt_id_fkey"
            columns: ["attempt_id"]
            isOneToOne: false
            referencedRelation: "assessment_attempts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assessment_answers_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "assessment_questions"
            referencedColumns: ["id"]
          }
        ]
      }
      assessment_attempts: {
        Row: {
          id: string
          assessment_id: string
          candidate_id: string
          status: Database["public"]["Enums"]["attempt_status"]
          started_at: string
          expires_at: string | null
          submitted_at: string | null
          question_ids: string[]
          ai_result: Json | null
          ai_level: Database["public"]["Enums"]["cefr_level"] | null
          final_level: Database["public"]["Enums"]["cefr_level"] | null
          final_score: number | null
          report: Json | null
          integrity: Json
          processing_attempts: number
          validated_by: string | null
          validated_at: string | null
          validation_comment: string | null
          visible_to_companies: boolean
          cooldown_waived: boolean
          created_at: string
          updated_at: string
          valid_until: string | null
        }
        Insert: {
          id?: string
          assessment_id: string
          candidate_id: string
          status?: Database["public"]["Enums"]["attempt_status"]
          started_at?: string
          expires_at?: string | null
          submitted_at?: string | null
          question_ids?: string[]
          ai_result?: Json | null
          ai_level?: Database["public"]["Enums"]["cefr_level"] | null
          final_level?: Database["public"]["Enums"]["cefr_level"] | null
          final_score?: number | null
          report?: Json | null
          integrity?: Json
          processing_attempts?: number
          validated_by?: string | null
          validated_at?: string | null
          validation_comment?: string | null
          visible_to_companies?: boolean
          cooldown_waived?: boolean
          created_at?: string
          updated_at?: string
          valid_until?: string | null
        }
        Update: {
          id?: string
          assessment_id?: string
          candidate_id?: string
          status?: Database["public"]["Enums"]["attempt_status"]
          started_at?: string
          expires_at?: string | null
          submitted_at?: string | null
          question_ids?: string[]
          ai_result?: Json | null
          ai_level?: Database["public"]["Enums"]["cefr_level"] | null
          final_level?: Database["public"]["Enums"]["cefr_level"] | null
          final_score?: number | null
          report?: Json | null
          integrity?: Json
          processing_attempts?: number
          validated_by?: string | null
          validated_at?: string | null
          validation_comment?: string | null
          visible_to_companies?: boolean
          cooldown_waived?: boolean
          created_at?: string
          updated_at?: string
          valid_until?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "assessment_attempts_assessment_id_fkey"
            columns: ["assessment_id"]
            isOneToOne: false
            referencedRelation: "assessments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assessment_attempts_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assessment_attempts_validated_by_fkey"
            columns: ["validated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      assessment_questions: {
        Row: {
          id: string
          assessment_id: string
          section: string
          band: Database["public"]["Enums"]["cefr_level"] | null
          sort_order: number
          prompt: string
          question_type: Database["public"]["Enums"]["question_type"]
          options: Json | null
          answer_key: Json | null
          weight: number
          factor: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          assessment_id: string
          section: string
          band?: Database["public"]["Enums"]["cefr_level"] | null
          sort_order?: number
          prompt: string
          question_type: Database["public"]["Enums"]["question_type"]
          options?: Json | null
          answer_key?: Json | null
          weight?: number
          factor?: string | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          assessment_id?: string
          section?: string
          band?: Database["public"]["Enums"]["cefr_level"] | null
          sort_order?: number
          prompt?: string
          question_type?: Database["public"]["Enums"]["question_type"]
          options?: Json | null
          answer_key?: Json | null
          weight?: number
          factor?: string | null
          is_active?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "assessment_questions_assessment_id_fkey"
            columns: ["assessment_id"]
            isOneToOne: false
            referencedRelation: "assessments"
            referencedColumns: ["id"]
          }
        ]
      }
      assessments: {
        Row: {
          id: string
          type: Database["public"]["Enums"]["assessment_type"]
          title: string
          description: string | null
          version: number
          is_active: boolean
          time_limit_minutes: number | null
          cooldown_days: number
          config: Json
          created_at: string
          validity_days: number
          required_to_apply: boolean
        }
        Insert: {
          id?: string
          type: Database["public"]["Enums"]["assessment_type"]
          title: string
          description?: string | null
          version?: number
          is_active?: boolean
          time_limit_minutes?: number | null
          cooldown_days?: number
          config?: Json
          created_at?: string
          validity_days?: number
          required_to_apply?: boolean
        }
        Update: {
          id?: string
          type?: Database["public"]["Enums"]["assessment_type"]
          title?: string
          description?: string | null
          version?: number
          is_active?: boolean
          time_limit_minutes?: number | null
          cooldown_days?: number
          config?: Json
          created_at?: string
          validity_days?: number
          required_to_apply?: boolean
        }
        Relationships: []
      }
      candidate_contacts: {
        Row: {
          candidate_id: string
          email: string | null
          phone: string | null
          linkedin_url: string | null
          portfolio_url: string | null
          resume_path: string | null
          updated_at: string
        }
        Insert: {
          candidate_id: string
          email?: string | null
          phone?: string | null
          linkedin_url?: string | null
          portfolio_url?: string | null
          resume_path?: string | null
          updated_at?: string
        }
        Update: {
          candidate_id?: string
          email?: string | null
          phone?: string | null
          linkedin_url?: string | null
          portfolio_url?: string | null
          resume_path?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "candidate_contacts_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: true
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          }
        ]
      }
      candidate_education: {
        Row: {
          id: string
          candidate_id: string
          institution: string
          degree: string | null
          field: string | null
          start_year: number | null
          end_year: number | null
        }
        Insert: {
          id?: string
          candidate_id: string
          institution: string
          degree?: string | null
          field?: string | null
          start_year?: number | null
          end_year?: number | null
        }
        Update: {
          id?: string
          candidate_id?: string
          institution?: string
          degree?: string | null
          field?: string | null
          start_year?: number | null
          end_year?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "candidate_education_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          }
        ]
      }
      candidate_experience: {
        Row: {
          id: string
          candidate_id: string
          company: string
          title: string
          start_date: string | null
          end_date: string | null
          is_current: boolean
          description: string | null
          sort_order: number
        }
        Insert: {
          id?: string
          candidate_id: string
          company: string
          title: string
          start_date?: string | null
          end_date?: string | null
          is_current?: boolean
          description?: string | null
          sort_order?: number
        }
        Update: {
          id?: string
          candidate_id?: string
          company?: string
          title?: string
          start_date?: string | null
          end_date?: string | null
          is_current?: boolean
          description?: string | null
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "candidate_experience_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          }
        ]
      }
      candidates: {
        Row: {
          id: string
          first_name: string
          last_name: string
          headline: string | null
          summary: string | null
          country: string
          city: string | null
          years_experience: number | null
          role_family: Database["public"]["Enums"]["role_family"] | null
          skills: string[]
          desired_roles: string[]
          desired_salary_min_usd: number | null
          availability: Database["public"]["Enums"]["availability"] | null
          preferred_contract_types: Database["public"]["Enums"]["contract_type"][]
          english_self_level: Database["public"]["Enums"]["cefr_level"] | null
          english_written_level: Database["public"]["Enums"]["cefr_level"] | null
          english_oral_level: Database["public"]["Enums"]["cefr_level"] | null
          english_verified_level: Database["public"]["Enums"]["cefr_level"] | null
          english_verified_at: string | null
          psychometric_completed_at: string | null
          profile_completeness: number
          visibility: Database["public"]["Enums"]["candidate_visibility"]
          candidate_tags: string[]
          data_consent_at: string
          data_consent_version: string
          created_at: string
          updated_at: string
          consent_flags: Json
        }
        Insert: {
          id: string
          first_name: string
          last_name: string
          headline?: string | null
          summary?: string | null
          country?: string
          city?: string | null
          years_experience?: number | null
          role_family?: Database["public"]["Enums"]["role_family"] | null
          skills?: string[]
          desired_roles?: string[]
          desired_salary_min_usd?: number | null
          availability?: Database["public"]["Enums"]["availability"] | null
          preferred_contract_types?: Database["public"]["Enums"]["contract_type"][]
          english_self_level?: Database["public"]["Enums"]["cefr_level"] | null
          english_written_level?: Database["public"]["Enums"]["cefr_level"] | null
          english_oral_level?: Database["public"]["Enums"]["cefr_level"] | null
          english_verified_level?: Database["public"]["Enums"]["cefr_level"] | null
          english_verified_at?: string | null
          psychometric_completed_at?: string | null
          profile_completeness?: number
          visibility?: Database["public"]["Enums"]["candidate_visibility"]
          candidate_tags?: string[]
          data_consent_at: string
          data_consent_version: string
          created_at?: string
          updated_at?: string
          consent_flags?: Json
        }
        Update: {
          id?: string
          first_name?: string
          last_name?: string
          headline?: string | null
          summary?: string | null
          country?: string
          city?: string | null
          years_experience?: number | null
          role_family?: Database["public"]["Enums"]["role_family"] | null
          skills?: string[]
          desired_roles?: string[]
          desired_salary_min_usd?: number | null
          availability?: Database["public"]["Enums"]["availability"] | null
          preferred_contract_types?: Database["public"]["Enums"]["contract_type"][]
          english_self_level?: Database["public"]["Enums"]["cefr_level"] | null
          english_written_level?: Database["public"]["Enums"]["cefr_level"] | null
          english_oral_level?: Database["public"]["Enums"]["cefr_level"] | null
          english_verified_level?: Database["public"]["Enums"]["cefr_level"] | null
          english_verified_at?: string | null
          psychometric_completed_at?: string | null
          profile_completeness?: number
          visibility?: Database["public"]["Enums"]["candidate_visibility"]
          candidate_tags?: string[]
          data_consent_at?: string
          data_consent_version?: string
          created_at?: string
          updated_at?: string
          consent_flags?: Json
        }
        Relationships: [
          {
            foreignKeyName: "candidates_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      companies: {
        Row: {
          id: string
          owner_user_id: string
          name: string
          legal_name: string | null
          website: string | null
          sector: Database["public"]["Enums"]["sector"] | null
          country: string
          state: string | null
          city: string | null
          size: Database["public"]["Enums"]["company_size"] | null
          description: string | null
          logo_path: string | null
          hiring_needs: Json
          status: Database["public"]["Enums"]["company_status"]
          verified_at: string | null
          verified_by: string | null
          created_at: string
          updated_at: string
          is_demo: boolean
        }
        Insert: {
          id?: string
          owner_user_id: string
          name: string
          legal_name?: string | null
          website?: string | null
          sector?: Database["public"]["Enums"]["sector"] | null
          country?: string
          state?: string | null
          city?: string | null
          size?: Database["public"]["Enums"]["company_size"] | null
          description?: string | null
          logo_path?: string | null
          hiring_needs?: Json
          status?: Database["public"]["Enums"]["company_status"]
          verified_at?: string | null
          verified_by?: string | null
          created_at?: string
          updated_at?: string
          is_demo?: boolean
        }
        Update: {
          id?: string
          owner_user_id?: string
          name?: string
          legal_name?: string | null
          website?: string | null
          sector?: Database["public"]["Enums"]["sector"] | null
          country?: string
          state?: string | null
          city?: string | null
          size?: Database["public"]["Enums"]["company_size"] | null
          description?: string | null
          logo_path?: string | null
          hiring_needs?: Json
          status?: Database["public"]["Enums"]["company_status"]
          verified_at?: string | null
          verified_by?: string | null
          created_at?: string
          updated_at?: string
          is_demo?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "companies_owner_user_id_fkey"
            columns: ["owner_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "companies_verified_by_fkey"
            columns: ["verified_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      company_members: {
        Row: {
          id: string
          company_id: string
          user_id: string | null
          invited_email: string | null
          role: Database["public"]["Enums"]["member_role"]
          invite_token: string | null
          invited_by: string | null
          accepted_at: string | null
          created_at: string
          invite_expires_at: string | null
        }
        Insert: {
          id?: string
          company_id: string
          user_id?: string | null
          invited_email?: string | null
          role?: Database["public"]["Enums"]["member_role"]
          invite_token?: string | null
          invited_by?: string | null
          accepted_at?: string | null
          created_at?: string
          invite_expires_at?: string | null
        }
        Update: {
          id?: string
          company_id?: string
          user_id?: string | null
          invited_email?: string | null
          role?: Database["public"]["Enums"]["member_role"]
          invite_token?: string | null
          invited_by?: string | null
          accepted_at?: string | null
          created_at?: string
          invite_expires_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "company_members_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "company_members_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "company_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      contact_requests: {
        Row: {
          id: string
          name: string
          email: string
          company: string | null
          request_type: string
          message: string | null
          locale: Database["public"]["Enums"]["locale"]
          ip_hash: string | null
          created_at: string
          role_to_fill: string | null
          seniority: Database["public"]["Enums"]["seniority"] | null
          budget_band: string | null
          needed_by: string | null
          status: Database["public"]["Enums"]["lead_status"]
          answered_at: string | null
          answered_by: string | null
          company_id: string | null
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          email: string
          company?: string | null
          request_type: string
          message?: string | null
          locale?: Database["public"]["Enums"]["locale"]
          ip_hash?: string | null
          created_at?: string
          role_to_fill?: string | null
          seniority?: Database["public"]["Enums"]["seniority"] | null
          budget_band?: string | null
          needed_by?: string | null
          status?: Database["public"]["Enums"]["lead_status"]
          answered_at?: string | null
          answered_by?: string | null
          company_id?: string | null
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string
          company?: string | null
          request_type?: string
          message?: string | null
          locale?: Database["public"]["Enums"]["locale"]
          ip_hash?: string | null
          created_at?: string
          role_to_fill?: string | null
          seniority?: Database["public"]["Enums"]["seniority"] | null
          budget_band?: string | null
          needed_by?: string | null
          status?: Database["public"]["Enums"]["lead_status"]
          answered_at?: string | null
          answered_by?: string | null
          company_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "contact_requests_answered_by_fkey"
            columns: ["answered_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contact_requests_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          }
        ]
      }
      data_requests: {
        Row: {
          id: string
          candidate_id: string
          kind: string
          status: string
          message: string | null
          resolved_by: string | null
          resolved_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          candidate_id: string
          kind: string
          status?: string
          message?: string | null
          resolved_by?: string | null
          resolved_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          candidate_id?: string
          kind?: string
          status?: string
          message?: string | null
          resolved_by?: string | null
          resolved_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "data_requests_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "data_requests_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      email_outbox: {
        Row: {
          id: string
          to: string
          template: string
          payload: Json
          locale: Database["public"]["Enums"]["locale"]
          status: string
          attempts: number
          last_error: string | null
          dedupe_key: string | null
          scheduled_for: string
          sent_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          to: string
          template: string
          payload?: Json
          locale?: Database["public"]["Enums"]["locale"]
          status?: string
          attempts?: number
          last_error?: string | null
          dedupe_key?: string | null
          scheduled_for?: string
          sent_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          to?: string
          template?: string
          payload?: Json
          locale?: Database["public"]["Enums"]["locale"]
          status?: string
          attempts?: number
          last_error?: string | null
          dedupe_key?: string | null
          scheduled_for?: string
          sent_at?: string | null
          created_at?: string
        }
        Relationships: []
      }
      job_commercials: {
        Row: {
          job_id: string
          client_bill_rate_usd: number | null
          placement_fee_usd: number | null
          internal_notes: string | null
          updated_by: string | null
          updated_at: string
        }
        Insert: {
          job_id: string
          client_bill_rate_usd?: number | null
          placement_fee_usd?: number | null
          internal_notes?: string | null
          updated_by?: string | null
          updated_at?: string
        }
        Update: {
          job_id?: string
          client_bill_rate_usd?: number | null
          placement_fee_usd?: number | null
          internal_notes?: string | null
          updated_by?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_commercials_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: true
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_commercials_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      jobs: {
        Row: {
          id: string
          company_id: string
          title: string
          slug: string | null
          role_family: Database["public"]["Enums"]["role_family"] | null
          seniority: Database["public"]["Enums"]["seniority"] | null
          description: string | null
          responsibilities: string | null
          requirements: string | null
          skills: string[]
          english_level_required: Database["public"]["Enums"]["cefr_level"] | null
          employment_type: Database["public"]["Enums"]["employment_type"] | null
          work_mode: Database["public"]["Enums"]["work_mode"]
          contract_type: Database["public"]["Enums"]["contract_type"] | null
          hours_per_week: number | null
          timezone_overlap: string | null
          start_date: string | null
          salary_min_usd: number | null
          salary_max_usd: number | null
          show_salary: boolean
          confidential_company: boolean
          status: Database["public"]["Enums"]["job_status"]
          review_message: string | null
          published_at: string | null
          closes_at: string | null
          created_by: string | null
          created_at: string
          updated_at: string
          reopen_snapshot: Json | null
        }
        Insert: {
          id?: string
          company_id: string
          title: string
          slug?: string | null
          role_family?: Database["public"]["Enums"]["role_family"] | null
          seniority?: Database["public"]["Enums"]["seniority"] | null
          description?: string | null
          responsibilities?: string | null
          requirements?: string | null
          skills?: string[]
          english_level_required?: Database["public"]["Enums"]["cefr_level"] | null
          employment_type?: Database["public"]["Enums"]["employment_type"] | null
          work_mode?: Database["public"]["Enums"]["work_mode"]
          contract_type?: Database["public"]["Enums"]["contract_type"] | null
          hours_per_week?: number | null
          timezone_overlap?: string | null
          start_date?: string | null
          salary_min_usd?: number | null
          salary_max_usd?: number | null
          show_salary?: boolean
          confidential_company?: boolean
          status?: Database["public"]["Enums"]["job_status"]
          review_message?: string | null
          published_at?: string | null
          closes_at?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
          reopen_snapshot?: Json | null
        }
        Update: {
          id?: string
          company_id?: string
          title?: string
          slug?: string | null
          role_family?: Database["public"]["Enums"]["role_family"] | null
          seniority?: Database["public"]["Enums"]["seniority"] | null
          description?: string | null
          responsibilities?: string | null
          requirements?: string | null
          skills?: string[]
          english_level_required?: Database["public"]["Enums"]["cefr_level"] | null
          employment_type?: Database["public"]["Enums"]["employment_type"] | null
          work_mode?: Database["public"]["Enums"]["work_mode"]
          contract_type?: Database["public"]["Enums"]["contract_type"] | null
          hours_per_week?: number | null
          timezone_overlap?: string | null
          start_date?: string | null
          salary_min_usd?: number | null
          salary_max_usd?: number | null
          show_salary?: boolean
          confidential_company?: boolean
          status?: Database["public"]["Enums"]["job_status"]
          review_message?: string | null
          published_at?: string | null
          closes_at?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
          reopen_snapshot?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "jobs_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      mock_interviews: {
        Row: {
          id: string
          candidate_id: string
          role_family: Database["public"]["Enums"]["role_family"]
          language: Database["public"]["Enums"]["locale"]
          status: Database["public"]["Enums"]["interview_status"]
          questions: Json
          answers: Json
          report: Json | null
          overall_score: number | null
          started_at: string
          expires_at: string
          completed_at: string | null
          processing_attempts: number
          created_at: string
          updated_at: string
          job_id: string | null
          transcript: Json
          candidate_turns: number
        }
        Insert: {
          id?: string
          candidate_id: string
          role_family: Database["public"]["Enums"]["role_family"]
          language?: Database["public"]["Enums"]["locale"]
          status?: Database["public"]["Enums"]["interview_status"]
          questions?: Json
          answers?: Json
          report?: Json | null
          overall_score?: number | null
          started_at?: string
          expires_at?: string
          completed_at?: string | null
          processing_attempts?: number
          created_at?: string
          updated_at?: string
          job_id?: string | null
          transcript?: Json
          candidate_turns?: number
        }
        Update: {
          id?: string
          candidate_id?: string
          role_family?: Database["public"]["Enums"]["role_family"]
          language?: Database["public"]["Enums"]["locale"]
          status?: Database["public"]["Enums"]["interview_status"]
          questions?: Json
          answers?: Json
          report?: Json | null
          overall_score?: number | null
          started_at?: string
          expires_at?: string
          completed_at?: string | null
          processing_attempts?: number
          created_at?: string
          updated_at?: string
          job_id?: string | null
          transcript?: Json
          candidate_turns?: number
        }
        Relationships: [
          {
            foreignKeyName: "mock_interviews_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mock_interviews_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          }
        ]
      }
      notes: {
        Row: {
          id: string
          candidate_id: string
          application_id: string | null
          author_user_id: string
          body: string
          visibility: Database["public"]["Enums"]["note_visibility"]
          created_at: string
        }
        Insert: {
          id?: string
          candidate_id: string
          application_id?: string | null
          author_user_id: string
          body: string
          visibility?: Database["public"]["Enums"]["note_visibility"]
          created_at?: string
        }
        Update: {
          id?: string
          candidate_id?: string
          application_id?: string | null
          author_user_id?: string
          body?: string
          visibility?: Database["public"]["Enums"]["note_visibility"]
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "notes_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notes_author_user_id_fkey"
            columns: ["author_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notes_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          }
        ]
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          title: string
          body: string | null
          link: string | null
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          title: string
          body?: string | null
          link?: string | null
          read_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          title?: string
          body?: string | null
          link?: string | null
          read_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      placements: {
        Row: {
          id: string
          application_id: string
          company_id: string
          candidate_id: string
          contract_type: Database["public"]["Enums"]["contract_type"]
          start_date: string
          end_date: string | null
          monthly_salary_usd: number
          monthly_bill_rate_usd: number
          status: Database["public"]["Enums"]["placement_status"]
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          application_id: string
          company_id: string
          candidate_id: string
          contract_type: Database["public"]["Enums"]["contract_type"]
          start_date: string
          end_date?: string | null
          monthly_salary_usd: number
          monthly_bill_rate_usd: number
          status?: Database["public"]["Enums"]["placement_status"]
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          application_id?: string
          company_id?: string
          candidate_id?: string
          contract_type?: Database["public"]["Enums"]["contract_type"]
          start_date?: string
          end_date?: string | null
          monthly_salary_usd?: number
          monthly_bill_rate_usd?: number
          status?: Database["public"]["Enums"]["placement_status"]
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "placements_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: true
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "placements_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "placements_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "placements_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      profiles: {
        Row: {
          id: string
          role: Database["public"]["Enums"]["user_role"]
          full_name: string | null
          email: string
          locale: Database["public"]["Enums"]["locale"]
          notification_prefs: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          role: Database["public"]["Enums"]["user_role"]
          full_name?: string | null
          email: string
          locale?: Database["public"]["Enums"]["locale"]
          notification_prefs?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          role?: Database["public"]["Enums"]["user_role"]
          full_name?: string | null
          email?: string
          locale?: Database["public"]["Enums"]["locale"]
          notification_prefs?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      saved_candidates: {
        Row: {
          company_id: string
          candidate_id: string
          created_by: string | null
          created_at: string
        }
        Insert: {
          company_id: string
          candidate_id: string
          created_by?: string | null
          created_at?: string
        }
        Update: {
          company_id?: string
          candidate_id?: string
          created_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "saved_candidates_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "saved_candidates_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "saved_candidates_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      candidate_cards: {
        Row: {
          id: string | null
          first_name: string | null
          last_initial: string | null
          headline: string | null
          summary: string | null
          city: string | null
          country: string | null
          years_experience: number | null
          role_family: Database["public"]["Enums"]["role_family"] | null
          skills: string[] | null
          desired_roles: string[] | null
          desired_salary_min_usd: number | null
          availability: Database["public"]["Enums"]["availability"] | null
          preferred_contract_types: Database["public"]["Enums"]["contract_type"][] | null
          english_self_level: Database["public"]["Enums"]["cefr_level"] | null
          english_written_level: Database["public"]["Enums"]["cefr_level"] | null
          english_oral_level: Database["public"]["Enums"]["cefr_level"] | null
          english_verified_level: Database["public"]["Enums"]["cefr_level"] | null
          english_verified_at: string | null
          psychometric_completed_at: string | null
          profile_completeness: number | null
          visibility: Database["public"]["Enums"]["candidate_visibility"] | null
          created_at: string | null
        }
        Relationships: []
      }
      public_jobs: {
        Row: {
          id: string | null
          title: string | null
          slug: string | null
          role_family: Database["public"]["Enums"]["role_family"] | null
          seniority: Database["public"]["Enums"]["seniority"] | null
          contract_type: Database["public"]["Enums"]["contract_type"] | null
          employment_type: Database["public"]["Enums"]["employment_type"] | null
          work_mode: Database["public"]["Enums"]["work_mode"] | null
          english_level_required: Database["public"]["Enums"]["cefr_level"] | null
          skills: string[] | null
          description: string | null
          responsibilities: string | null
          requirements: string | null
          hours_per_week: number | null
          timezone_overlap: string | null
          start_date: string | null
          salary_min_usd: number | null
          salary_max_usd: number | null
          show_salary: boolean | null
          confidential_company: boolean | null
          company_name: string | null
          company_logo_path: string | null
          company_sector: Database["public"]["Enums"]["sector"] | null
          company_size: Database["public"]["Enums"]["company_size"] | null
          published_at: string | null
          closes_at: string | null
        }
        Relationships: []
      }
      public_jobs_closed: {
        Row: {
          id: string | null
          title: string | null
          slug: string | null
          role_family: Database["public"]["Enums"]["role_family"] | null
          seniority: Database["public"]["Enums"]["seniority"] | null
          company_name: string | null
          published_at: string | null
          closed_at: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      assessment_cooldown_ok: {
        Args: { target_assessment_id: string; target_candidate_id: string }
        Returns: string
      }
      candidate_application_jobs: {
        Args: Record<PropertyKey, never>
        Returns: unknown[]
      }
      candidate_apply_requirements: {
        Args: { target_candidate_id: string }
        Returns: unknown[]
      }
      candidate_valid_results: {
        Args: { target_candidate_id: string }
        Returns: unknown[]
      }
      cefr_min: {
        Args: { a: Database["public"]["Enums"]["cefr_level"]; b: Database["public"]["Enums"]["cefr_level"] }
        Returns: Database["public"]["Enums"]["cefr_level"]
      }
      cefr_rank: {
        Args: { level: Database["public"]["Enums"]["cefr_level"] }
        Returns: number
      }
      slugify: {
        Args: { input: string }
        Returns: string
      }
    }
    Enums: {
      application_source: "candidate" | "dexee_recommended"
      application_status: "applied" | "screening" | "shortlisted" | "interview" | "offer" | "hired" | "rejected" | "withdrawn"
      assessment_type: "english_written" | "english_oral" | "psychometric" | "disc"
      attempt_status: "in_progress" | "submitted" | "processing" | "ai_scored" | "pending_validation" | "validated" | "expired" | "failed"
      availability: "immediate" | "two_weeks" | "one_month" | "three_months"
      candidate_visibility: "visible_to_companies" | "dexee_only"
      cefr_level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2"
      company_size: "s1_10" | "s11_50" | "s51_200" | "s201_1000" | "s1000_plus"
      company_status: "pending" | "verified" | "suspended"
      contract_type: "independent_contractor" | "dexee_eor" | "direct_hire" | "project_based"
      employment_type: "full_time" | "part_time"
      interview_status: "in_progress" | "completed" | "failed" | "expired"
      job_status: "draft" | "pending_review" | "changes_requested" | "published" | "paused" | "closed"
      lead_status: "new" | "answered" | "converted" | "discarded"
      locale: "en" | "es"
      member_role: "owner" | "member"
      note_visibility: "company" | "dexee_only"
      placement_status: "active" | "ended"
      question_type: "mcq" | "writing" | "audio" | "likert" | "situational"
      role_family: "finance_accounting" | "software_engineering" | "data" | "customer_support" | "sales_sdr" | "marketing" | "design" | "operations_va" | "hr" | "legal" | "project_management" | "other"
      sector: "technology" | "financial_services" | "healthcare" | "professional_services" | "marketing" | "ecommerce_retail" | "real_estate" | "logistics" | "manufacturing" | "education" | "legal" | "other"
      seniority: "junior" | "mid" | "senior" | "lead"
      user_role: "company" | "candidate" | "admin"
      work_mode: "remote" | "hybrid" | "onsite"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database["public"]

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Views<T extends keyof PublicSchema["Views"]> = PublicSchema["Views"][T]["Row"]
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T]
